services:
  - type: web
    name: unifind
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseProvider
        value: Sqlite
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=UniversityLostAndFound.db
      - key: AdminSeed__Email
        sync: false
      - key: AdminSeed__Password
        sync: false
      - key: StudentSeed__Email
        sync: false
      - key: StudentSeed__Password
        sync: false
